server:
  port: 80

spring:
  mail:
    host: smtp.qq.com
    username: 812699803@QQ.com
    password: ymaqbuaqcfwibejd
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

