server:
  port: 8080
  servlet:
    context-path: /web
spring:
  datasource:
    druid:
      db1:
        # 数据库访问配置, 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/orcl?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 连接等待超时时间
        max-wait: 30000
      db2:
        # 数据库访问配置, 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/orcl2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 连接池配置
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 连接等待超时时间
        max-wait: 30000
