server:
  port: 80
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/orcl?serverTimezone=UTC&useUnicode=true&characterEndcoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
logging:
  level:
    com:
      example:
        springbootehcache:
           mapper:
             debug

